spring.application.name=energy-producer

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

weather.api.url=https://api.open-meteo.com/v1/forecast?latitude=48.2082&longitude=16.3738&current=direct_radiation,cloud_cover&timezone=Europe%2FVienna